#!/bin/sh
#
# jcc - simple script for compiling java procjects

if [ "$#" -ne "2" ]; then
  printf "$0: Error. Invalid number of arguments specified.\n"
  printf "try jcc [option] [class name]\n"
  exit 1
fi

if [ "$1" = "build" ]; then
  javac -d "bin" "src/$2.java"
elif [ "$1" = "run" ]; then
  java -cp "bin" "$2"
else
  printf "Option: $1 not found.\n"
fi
