#!/bin/sh

if [ "$#" -ne "1" ] ; then
  printf "Invalid input. Try jcc-grades build to compile or jcc-grades run to run.\n"
fi

if [ "$1" = "build" ] ; then
  javac -d "bin" \
    "src/grades/Student.java" \
    "src/grades/GradesApplication.java"
  printf "Build complete.\n"
elif [ "$1" = "run" ] ; then
  cd "bin"
  java -cp ".:grades" "grades/GradesApplication"
  cd ..
fi
